"""Initial migration - create all tables

Revision ID: db14ca35350e
Revises:
Create Date: 2025-06-30 15:11:57.114183

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "db14ca35350e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
